import mediapipe
import cv2
import pygame

"""Configuration settings for the Fireball Hand Gesture application"""

# Camera Settings
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30
CAMERA_INDEX = 0  # 0 for default camera

# Hand Detection
HAND_DETECTION_CONFIDENCE = 0.7
HAND_TRACKING_CONFIDENCE = 0.7
MAX_HANDS = 2

# Fireball Physics
FIREBALL_INITIAL_SIZE = 30
FIREBALL_MAX_SIZE = 50
FIREBALL_LIFETIME = 300  # frames
FIREBALL_GRAVITY = 0.1
FIREBALL_FRICTION = 0.98
MAX_ACTIVE_FIREBALLS = 10

# Gesture Detection
HAND_OPEN_THRESHOLD = 30  # pixels
THROW_VELOCITY_THRESHOLD = 15  # pixels/frame
THROW_COOLDOWN = 10  # frames

# Visual Effects
PARTICLE_POOL_SIZE = 100
EXPLOSION_INTENSITY = 40
FLASH_DURATION = 30  # frames
FLASH_INTENSITY = 100
TRAIL_MAX_LENGTH = 15

# UI
SHOW_DEBUG_INFO = True
SHOW_HUD = True
SHOW_HAND_LANDMARKS = False

# Colors (RGB)
COLOR_FIREBALL = (255, 120, 0)
COLOR_FIREBALL_INNER = (255, 200, 0)
COLOR_FIREBALL_CORE = (255, 255, 100)
COLOR_EXPLOSION = (255, 150, 0)
COLOR_BACKGROUND = (10, 10, 20)
COLOR_TEXT_PRIMARY = (255, 255, 0)
COLOR_TEXT_SECONDARY = (200, 200, 200)

# Performance
TARGET_FPS = 30
ENABLE_FRAME_SKIP = False

# Debug
DEBUG_PRINT_FRAMES = False
DEBUG_HAND_POSITIONS = False
DEBUG_VELOCITY = False
DEBUG_COLLISION = False
